### ISSUE TITLE
Key size exceptions in Java 21

### ISSUE THREAD

**Issue by atmcq** [alphagov/notifications-java-client#252]
We are seeing the following errors in our test environment since upgrading our app to Java 21. I've not got access to the GovNotify admin that our customer manages, so apologies if the key length is under their control, but thought I should flag this while we wait to hear back.

```
java.lang.RuntimeException: org.jose4j.lang.InvalidKeyException: A key of the same size as the hash output (i.e. 256 bits for HS256) or larger MUST be used with the HMAC SHA algorithms but this key is only 104 bits
	at uk.gov.service.notify.Authentication.create(Authentication.java:33)
	at uk.gov.service.notify.NotificationClient.createConnectionAndSetHeaders(NotificationClient.java:399)
	at uk.gov.service.notify.NotificationClient.sendSms(NotificationClient.java:191)
```

**Comment by atmcq** [comment]
We've raised a query with the GovNotify support team and they confirm that the key size should be long enough. Customer does not think they are actually using this service so we suspect there is some old test data in there. Therefore closing this issue.
